### ISSUE TITLE
rake aborted! Errno::EMFILE

### ISSUE THREAD

**Issue by iamavi7** [inertia186/drotto#15]
rake aborted!
Errno::EMFILE: Failed to open TCP connection to steemd.steemit.com:443 (Too many open files - getaddrinfo)
/root/drotto/lib/drotto/bounce_job.rb:32:in `init_transactions'
/root/drotto/lib/drotto/bounce_job.rb:14:in `initialize'
/root/drotto/lib/drotto.rb:35:in `new'
/root/drotto/lib/drotto.rb:35:in `find_bids'
/root/drotto/lib/drotto.rb:202:in `block in run'
/root/drotto/lib/drotto.rb:195:in `loop'
/root/drotto/lib/drotto.rb:195:in `run'
/root/drotto/Rakefile:66:in `block in <top (required)>'
/root/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/root/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

Caused by:
Errno::EMFILE: Too many open files - getaddrinfo
/root/drotto/lib/drotto/bounce_job.rb:32:in `init_transactions'
/root/drotto/lib/drotto/bounce_job.rb:14:in `initialize'
/root/drotto/lib/drotto.rb:35:in `new'
/root/drotto/lib/drotto.rb:35:in `find_bids'
/root/drotto/lib/drotto.rb:202:in `block in run'
/root/drotto/lib/drotto.rb:195:in `loop'
/root/drotto/lib/drotto.rb:195:in `run'
/root/drotto/Rakefile:66:in `block in <top (required)>'
/root/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/root/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => run
(See full trace by running task with --trace)

**Comment by inertia186** [comment]
As a work-around, you can use:

```bash
rake bounce_once[3000]
```

Also related: https://steemit.com/bots/@inertia/detect-hung-sh
