### ISSUE TITLE
Custom usage rules - auto-bounce all invalid bids

### ISSUE THREAD

**Issue by bitcoiners** [inertia186/drotto#7]
We need to be able to **auto-bounce all invalid bids.**  

Current Usage rules:
If there are multiple bids with the same post, only one vote will be cast and the remaining bids will not be returned.
If the bot has already voted for a post, additional bids will not be returned.
The URL must be correctly expressed in the memo alone. Malformed memos will not be returned.
I would like to auto-refund bids under all listed conditions, it would reduce manual refunds. 
Would be useful to be able to set usage rules in config.

**Comment by inertia186** [comment]
do a pull request

**Comment by inertia186** [comment]
You might prefer to use:

https://github.com/MattyIce/postpromoter

**Comment by bitcoiners** [comment]
Thanks. I will give it a try.
